server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），
      # 缺省:30分钟，建议设置比数据库超时时长少30秒，
      # 参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 28830000
      # 连接池中允许的最大连接数。缺省值：10；
      # 推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 9
  rabbitmq:
    host: 45.63.53.242
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    #5秒钟发送一次心跳
    lease-renewal-interval-in-seconds: 5
    #10秒不发送就过期
    lease-expiration-duration-in-seconds: 10
mybatis:
  type-aliases-package: com.leyou.item.pojo
