server:
  port: 10086
spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    #不显示eureka自身的微服务
    register-with-eureka: false #把自己注册到eureka服务列表
    fetch-registry: false #拉取eureka服务信息
  server:
    #关闭自我保护模式
    enable-self-preservation: false
    #定期清理无效链接  10s
    eviction-interval-timer-in-ms: 10000

